Docker analysis refactoring
sfu-ireceptor/gateway pull request #446
Opened 2021-07-13 21:12 UTC by bcorrie

To be reviewed by @jeromejaglale

2021-07-14 21:15 UTC, jeromejaglale requested changes
Added some comments on JIRA: https://ireceptor.atlassian.net/browse/IR-2483

2021-07-15 22:31 UTC, bcorrie commented on app/Agave.php
> +        $app_directories = config('services.agave.app_directories');
No, I don't think so... I though of doing that, but I thought it safer to be explicit. That way we are sure that what we are running through the Gateway is intentional and precise. With a config we can have development apps that are not in production, can temporarily add/remove apps easily, without touching the files/directories...

In addition, with singularity, from a security standpoint, I think we want to be very careful about what we run as Apps. So scanning a directory could be risky. The way I have it, the Gateway config controls which apps are run, and the Gateway separately controls which singularity images are used (they aren't bundled with the app). This makes it very difficult for someone to add a rogue singularity image or a rogue app that does something bad.

2021-07-15 22:33 UTC, bcorrie commented on app/Jobs/LaunchAgaveJob.php
> +            Log::debug('#### HELLLOOOOOO');
8-) From when I was trying to recall the Laravel framework and how the components worked together. I couldn't figure out where this code was being called from. Will remove. 8-)

2021-07-15 22:42 UTC, bcorrie commented on app/Jobs/LaunchAgaveJob.php
> +            Log::debug('#### HELLLOOOOOO');
Fixed...

2021-07-15 22:43 UTC, bcorrie commented on resources/views/sequence.blade.php
> +	<h1>2. SSSSSequence Search</h1>
Nope, intentional - again making sure I new I was changing the correct code from my early explorations. My internal way of knowing I was on the Analysis sequence page 8-)

Shouldn't be part of the end product though - and I don't think I need it any more 8-)

2021-07-15 22:47 UTC, bcorrie commented on resources/views/sequence.blade.php
> +	<h1>2. SSSSSequence Search</h1>
Fixed.

2021-07-15 22:49 UTC, bcorrie commented on app/Agave.php
> +            $files = scandir('.');
Yep, was used in a debug statements earlier... fixed...

2021-07-15 22:49 UTC, bcorrie commented on app/Agave.php
> +        $app_directories = config('services.agave.app_directories');
@jeromejaglale does that make sense...

2021-07-16 20:48 UTC, closed without merging